### ISSUE TITLE
How does Serverless-Offline integration work?

### ISSUE THREAD

**Issue by TriangularCube** [epsagon/serverless-package-external#10]
The readme indicates the package works with serverless-offline, but I see no indication of any symlinks being created when invoking serverless-offline, nor does importing a local package from elsewhere work (a error about missing module is given). Is there a manual step I'm missing?

The package works fine when actually packaging to deploy, just not for offline testing.

**Comment by ranrib** [comment]
@BorjaMacedo added the support for that in here https://github.com/epsagon/serverless-package-external/commit/02b3eaed8622617e02496e2fcc993c937689512c
Can you maybe elaborate @BorjaMacedo ?

**Comment by BorjaMacedo** [comment]
Can you tell us which command does not work?

**Comment by TriangularCube** [comment]
Ah, it looks like my mistake. Evidently `sls offline` and `sls offline start` are not synonymous. I've been using the former and the symlink hooks only fire on the latter. Thanks everyone.
