### ISSUE TITLE
does not work with sls offline (without start)

### ISSUE THREAD

**Issue by ciekawy** [epsagon/serverless-package-external#30]
some plugins like `serverless-s3-local` ,  `serverless-dynamodb-local` follow different lifecycle and they do stop for `offline:start:end` - the only way to use them is to do `sls offline` without `start` param. Also `start` triggers daemon mode while no `start` runs offline in pending mode waiting for Ctrl-C which is useful in some cases

to make this great plugin working also without `start` param there should be added
```
"before:offline:start": this.beforeDeploy.bind(this)
```

**Comment by ciekawy** [comment]
any chances to get it merged?

**Comment by ghost** [comment]
This would be great if we could get it merged. I am having the same issues.

**Comment by ciekawy** [comment]
@C-reddd temporarily I'm using `patch-package` (with just the single line mentioned above).

**Comment by ghost** [comment]
@ciekawy Thanks for the reply. However, I am not sure I am following 100%. How have you fixed this? I am not sure what `patch-package` is. Sorry for the confusion

**Comment by ranrib** [comment]
Thanks! 💯
