### ISSUE TITLE
 EPERM: operation not permitted, scandir

### ISSUE THREAD

**Issue by kyeljmd** [epsagon/serverless-package-external#6]
just installed the plugin and currently using it in with windows. and I have encountered this issue with the library.

`Serverless: [serverless-package-external] Symlinking ../shared_code
Serverless: [serverless-package-external] is complete
Serverless: Packaging service...

  Error --------------------------------------------------

  EPERM: operation not permitted, scandir 'C:\mydir\shared_code'`

**Comment by ronyis** [comment]
We haven't tried the plugin on Windows.
It seems that after symlinking the external folder, there is a problem for the `serverless` process to read it because of permissions. Maybe try to make sure it has the permissions to do do.

**Comment by ranrib** [comment]
Hi @kyeljmd can you check the permissions issue as @ronyis mentioned please? thanks!
