### ISSUE TITLE
local testing

### ISSUE THREAD

**Issue by webchaz** [epsagon/serverless-package-external#7]
Hello, 

Is there anyway to test locally with this? Such as running test cases the paths don't resolve since it's only done when packaged.

Thank you

**Comment by ranrib** [comment]
Hi there,

Do you use any plugin for local testing? or do you run the local test outside of `serverless`?
If it outside - you can add the path to the external package. If it's via any other plugin, I guess the support can be added, but it will require a research.

Thanks @webchaz
